Siting fixed
BuyMyBeard/Neon-Souls pull request #12
Opened 2023-09-23 20:00 UTC by JeremyDeschamps

2023-09-29 04:37 UTC, BuyMyBeard requested changes
Le code est beau pour l'instant, mais quand on merge dans main, fix IsDying dans Health.cs.

Je pense juste qu'on devrait avoir le modèle du arcade cabinet et lui appliquer le shader de hologram avec une animation de flotter en tournant dans les airs avant de push dans le main

2023-10-02 21:51 UTC, JohnP55 requested changes

2023-10-02 21:51 UTC, JohnP55 commented on Assets/Scripts/Manager/GameManager.cs
> +using System.Collections;using System.Collections.Generic;using System.Linq;using System.Runtime.CompilerServices;using Unity.VisualScripting;using UnityEngine;public class GameManager : MonoB
?????????????????

2023-10-02 21:51 UTC, JohnP55 commented on Assets/Scripts/Environment/Lever.cs
> +    }
les overrides sont pas nécessaires

2023-10-02 21:51 UTC, JohnP55 commented on Assets/Scripts/Manager/BonFireManager.cs
> +    }
SetRepawn

2023-10-02 21:51 UTC, JohnP55 commented on Assets/Scripts/Manager/BonFireManager.cs
> +        playerCharacter.enabled = true;
Ici est-ce que c'est utile de désactiver et réactiver le playerCharacter dans la même fonction?

2023-10-04 18:03 UTC, JohnP55 requested changes
Je fais le review pour me documenter mais je vais les faire live

2023-10-04 18:14 UTC, JohnP55 commented on Assets/Scripts/Manager/BonFireManager.cs
> +    }
Done

2023-10-04 18:16 UTC, JohnP55 commented on Assets/Scripts/UI/ButtonPrompt.cs
>          // TODO: link this to input manager
Done

2023-10-04 20:04 UTC, BuyMyBeard approved these changes
8===D

2023-10-04 20:04 UTC, merged