Camera lock on
BuyMyBeard/Neon-Souls pull request #13
Opened 2023-09-28 00:13 UTC by Dzubrul

Job well done svp!

2023-09-29 04:05 UTC, BuyMyBeard approved these changes
J'ai refactor pas mal tout LockOn, pi rajouté du behavior pour délock automatiquement quand l'ennemi est mort, en fesant linger la barre de vie. Aussi une coupe de bugfixes.

Il va falloir revenir sur le tracking de VCam, rn c'est dizzying quand tu est lock on sur un ennemi et tu tournes autour

2023-10-02 21:41 UTC, JohnP55 requested changes
C'est all good, y'a juste un petit changement à faire

2023-10-02 21:41 UTC, JohnP55 commented on Assets/Scripts/Character/Player/LockOn.cs
> +        else if (!IsLocked && enemiesInSight.Count > 0)
pas besoin de vérifier deux fois IsLocked et !IsLocked

2023-10-02 23:31 UTC, Dzubrul commented on Assets/Scripts/Character/Player/LockOn.cs
> +        else if (!IsLocked && enemiesInSight.Count > 0)
Testé et t'as raison, j'ai enlever le !IsLocked dans le dernier commit

2023-10-03 01:14 UTC, merged